### ISSUE TITLE
Configuration 

### ISSUE THREAD

**Issue by nicolerg** [sbbi/MDS2#1]
Hello, I'm trying to get this version of MDS2 running on my linux machine because the online version doesn't support more than 300 input sequences. I have a couple of questions about how to get the software working.

1. In step 1 of the instructions ("Make links of uniprobe2meme and tomtom using cmd: "ln -s [MEME_folder]/bin/uniprobe2meme ." "ln -s [MEME_folder]/bin/tomtom") what directory is MEME_folder referring to?
2. Step 11 says "Background of RNA and miRNA data is required. They can be found here:", but there is no link or information for where to find background miRNA data. Can this still be found anywhere?

Thanks in advance.

**Comment by nicolerg** [comment]
I figured out the answer to my first question, but it would be helpful to include the MEME suite in the list of dependencies.

**Comment by nicolerg** [comment]
A few other dependencies and instructions that should be included to make this software more accessible:

Dependencies:
1. R igraph library
2. GCC v7+ (specifically for libgfortran.so.4)
3. MEME v 4.11.2 or lower (or at least version meme-5.0.1 doesn't include ./bin/uniprobe2meme)
4. weblogo python package 

Other important instructions:
1. the negative sequence input file must be renamed to negSeq.fa and moved to `inputFolder`
2. GraphBasedMotifFinding.py must be run from within the MDS2 directory to avoid the following error (alternatively, if calling it within a script, add the line `cd $MDS2_dir` before call):
`Traceback (most recent call last):
  File "/users/nicolerg/MDS2/GraphBasedMotifFinding.py", line 16, in <module>
    logging.config.fileConfig('loggingConf.ini')
  File "/users/nicolerg/anaconda2/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/users/nicolerg/anaconda2/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/users/nicolerg/anaconda2/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'`
3. run `chmod +x gs-921-linux-x86_64` after copying `gs-921-linux-x86_64` to the MDS2 directory to add execution permissions

**Comment by nicolerg** [comment]
More dependencies:
- MEME v 4.11.2 or lower (or at least version meme-5.0.1 doesn't include ./bin/uniprobe2meme
- weblogo python package
